baseURL = "https://divineugorji.netlify.app/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Divine"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1

[[menu.main]]
name = "About"
url = "#about"
weight = 2

[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5

[[menu.main]]
name = "Blog"
url = "#blog"
weight = 6

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1

[[menu.sitemap]]
name = "Porfolio"
url = "portfolio"
weight = 2

[[menu.sitemap]]
name = "Latest Article"
url = "blog"
weight = 3

[[menu.sitemap]]
name = "Contact"
url = "contact"
weight = 5

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © divineugorji.tech 2021"
footerLogo = "images/contact/code.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/code.png"

[params.address]
address = "Aba, Abia State, Nigeria."
email = "divineugorji37@gmail.com"
openingHours = "Open 24/7 everyday"
phone = "+(234) 814 4316 863"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/divine-ugorji/"
weight = 1

[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/codeSuperstarr"
weight = 2
